routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Back\Master\TaskController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Credential\CredentialController;
use App\Http\Controllers\Credential\ProfileController;
use App\Http\Controllers\Back\Master\DivisiController;
use App\Http\Controllers\Back\Master\CheckpointController;
use App\Http\Controllers\Back\Ktp\KtpController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();
Route::get('helper/download', [\App\Http\Controllers\Back\HelperController::class, 'download'])->name('helper.download');

Route::group(['middleware' => ['auth']], function () {

        Route::resource('users', CredentialController::class)->middleware('role:administrator');
        Route::resource('profile', ProfileController::class);


        Route::resource('gudang', \App\Http\Controllers\Back\Master\GudangController::class);
        Route::resource('people', \App\Http\Controllers\Back\Master\PeopleController::class);
        Route::resource('kategori', \App\Http\Controllers\Back\Master\KategoriController::class);
        Route::resource('item', \App\Http\Controllers\Back\Master\ItemController::class);
        Route::resource('satuan', \App\Http\Controllers\Back\Master\SatuanController::class);
        Route::get('asset-user', [\App\Http\Controllers\Back\UserItemController::class, 'index'])
            ->name('asset-user.index');
        Route::get('asset-user-assign', [\App\Http\Controllers\Back\UserItemController::class, 'assign'])
            ->name('asset-user-assign.index');
        Route::delete('asset-user-unassign', [\App\Http\Controllers\Back\UserItemController::class, 'unAssignItem'])
            ->name('asset-user-unassign.index');
        Route::post('asset-user/store', [\App\Http\Controllers\Back\UserItemController::class, 'assignItem'])
            ->name('asset-user.store');
    });

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Satuan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Satuan extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/Back/Master/GudangController.php
<?php

namespace App\Http\Controllers\Back\Master;

use App\Http\Controllers\Controller;
use App\Http\Requests\Master\Gudang\CreateRequest;
use App\Http\Requests\Master\Gudang\UpdateRequest;
use App\Models\Gudang;
use Illuminate\Http\Request;
use DataTables;
use Session;

class GudangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $data = Gudang::select('*');
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($a) {
                    return '<a href="' . route('gudang.edit', $a->id) . '" class="primary edit mr-1"><i class="fa fa-pencil mr-2"></i></a>
                            <a href="' . route('gudang.destroy', $a->id) . '" class="danger delete delete-data-table mr-1" ><i class="fa fa-trash mr-2"></i></a>';
                })
                ->make(true);
        }

        return view('page.master.gudang.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('page.master.gudang.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $data = Gudang::create(
            [
                'name' => $request->name,
                'alamat' => $request->alamat,
            ]
        );

        if($data){
            Session::flash('keterangan', 'Data berhasil di simpan');
        }

        return redirect()->route('gudang.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Gudang::find($id);

        return view('page.master.gudang.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $data = Gudang::find($id)
            ->update($request->except('_token', '_method', 'proengsoft_jsvalidation'));
        if($data){
            Session::flash('keterangan', 'Data berhasil di simpan');
        }

        return redirect()->route('gudang.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Gudang::destroy($id);

        return $data;
    }
}

app/Http/Controllers/Back/Master/ItemController.php
<?php

namespace App\Http\Controllers\Back\Master;

use App\Http\Controllers\Controller;
use App\Http\Requests\Master\Item\CreateRequest;
use App\Http\Requests\Master\Item\UpdateRequest;
use App\Models\Gudang;
use App\Models\Item;
use App\Models\kategori;
use App\Models\Satuan;
use Illuminate\Http\Request;
use DataTables;
use Session;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use Carbon\Carbon;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {

            $data = Item::with(['gudang', 'kategori', 'satuan'])->select('*');

            $data = Item::with(['gudang', 'kategori'])->select('*');
            if($request->has('users')){
                $data->where('users_id', '=', auth()->user()->id);
            }
            if($request->has('users_id')){
                $data->where('users_id', '=', $request->users_id);
            }
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($a) {
                    return '<a href="' . route('item.edit', $a->id) . '" class="primary edit mr-1"><i class="fa fa-pencil mr-2"></i></a>
                            <a href="' . route('item.show', $a->id) . '" class="primary edit mr-1"><i class="fa fa-eye mr-2"></i></a>
                            <a href="' . route('item.destroy', $a->id) . '" class="danger delete delete-data-table mr-1" ><i class="fa fa-trash mr-2"></i></a>';
                })->addColumn('action2', function ($a) {
                    return '<a href="' . route('asset-user-unassign.index', ['item_id' => $a->id]) . '" class="danger delete delete-data-table mr-1" ><i class="fa fa-trash mr-2"></i></a>';
                })->addColumn('depresiasi', function ($a) {
                    $startDate = Carbon::parse($a->tanggal_pengadaan);
                    $endDate = Carbon::parse(date('Y-m-d'));
                    $diff = $startDate->diffInYears($endDate);

                    $persen = 100 / $a->estimasi_pakai;
                    $nilai= $a->nilai_barang * $persen / 100;
                    return $nilai * $diff;
                })->addColumn('nilai_akhir', function ($a) {
                    $startDate = Carbon::parse($a->tanggal_pengadaan);
                    $endDate = Carbon::parse(date('Y-m-d'));
                    $diff = $startDate->diffInYears($endDate);

                    $persen = 100 / $a->estimasi_pakai;
                    $nilai= $a->nilai_barang * $persen / 100;
                    return $a->nilai_barang -  ($nilai * $diff);
                })
                ->addColumn('qr', function ($a) {
                    return QrCode::generate($a->kode);;
                })
                ->rawColumns(['action', 'qr', 'action2'])
                ->make(true);
        }

        return view('page.master.item.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $gudang = Gudang::pluck('name', 'id');
        $kategori = kategori::pluck('name', 'id');
        $satuan = Satuan::pluck('name', 'id');

        return view('page.master.item.create', compact('gudang', 'kategori', 'satuan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $data = Item::create(
           $request->all()
        );

        if($data){
            Session::flash('keterangan', 'Data berhasil di simpan');
        }

        return redirect()->route('item.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Item::with(['gudang', 'kategori', 'satuan'])->find($id);


        return view('page.master.item.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Item::find($id);
        $gudang = Gudang::pluck('name', 'id');
        $kategori = kategori::pluck('name', 'id');
        $satuan = Satuan::pluck('name', 'id');

        return view('page.master.item.edit', compact('data','gudang', 'kategori', 'satuan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $data = Item::find($id)
            ->update($request->except('_token', '_method', 'proengsoft_jsvalidation'));
        if($data){
            Session::flash('keterangan', 'Data berhasil di simpan');
        }

        return redirect()->route('item.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Item::destroy($id);

        return $data;
    }
}

app/Http/Controllers/Back/Master/KategoriController.php
<?php

namespace App\Http\Controllers\Back\Master;

use App\Http\Controllers\Controller;
use App\Http\Requests\Master\Kategori\CreateRequest;
use App\Http\Requests\Master\Kategori\UpdateRequest;
use App\Models\kategori;
use Illuminate\Http\Request;
use DataTables;
use Session;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $data = kategori::select('*');
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($a) {
                    return '<a href="' . route('kategori.edit', $a->id) . '" class="primary edit mr-1"><i class="fa fa-pencil mr-2"></i></a>
                            <a href="' . route('kategori.destroy', $a->id) . '" class="danger delete delete-data-table mr-1" ><i class="fa fa-trash mr-2"></i></a>';
                })
                ->make(true);
        }

        return view('page.master.kategori.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('page.master.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $data = kategori::create(
            [
                'name' => $request->name,
            ]
        );

        if($data){
            Session::flash('keterangan', 'Data berhasil di simpan');
        }

        return redirect()->route('kategori.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = kategori::find($id);

        return view('page.master.kategori.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $data = kategori::find($id)
            ->update($request->except('_token', '_method', 'proengsoft_jsvalidation'));
        if($data){
            Session::flash('keterangan', 'Data berhasil di simpan');
        }

        return redirect()->route('kategori.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = kategori::destroy($id);

        return $data;
    }
}

app/Http/Controllers/Back/Master/PeopleController.php
<?php

namespace App\Http\Controllers\Back\Master;

use App\Http\Controllers\Controller;
use App\Http\Requests\Master\People\CreateRequest;
use App\Http\Requests\Master\People\UpdateRequest;
use App\Models\People;
use Illuminate\Http\Request;
use DataTables;
use Session;

class PeopleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $data = People::select('*');
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($a) {
                    return '<a href="' . route('people.edit', $a->id) . '" class="primary edit mr-1"><i class="fa fa-pencil mr-2"></i></a>
                            <a href="' . route('people.destroy', $a->id) . '" class="danger delete delete-data-table mr-1" ><i class="fa fa-trash mr-2"></i></a>';
                })
                ->make(true);
        }

        return view('page.master.people.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('page.master.people.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        $data = People::create(
            [
                'name' => $request->name,
                'email' => $request->email,
                'telepon' => $request->telepon,
                'alamat' => $request->alamat,
            ]
        );

        if($data){
            Session::flash('keterangan', 'Data berhasil di simpan');
        }

        return redirect()->route('people.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = People::find($id);

        return view('page.master.people.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        $data = People::find($id)
            ->update($request->except('_token', '_method', 'proengsoft_jsvalidation'));
        if($data){
            Session::flash('keterangan', 'Data berhasil di simpan');
        }

        return redirect()->route('people.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = People::destroy($id);

        return $data;
    }
}

resources/views/page/master/satuan/create.blade.php
@extends('layouts.app')

@section('content')
    <section id="description" class="card">
        <div class="card-header">
            <h4 class="card-title">Satuan</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                {!! Form::open(['route' => 'satuan.store','files' => true, 'id' => 'form-task'])!!}

                <div class="form-body">
                    <div class="row">
                        <div class="col md-6">
                            <div class="form-group">
                                {!! Form::label('name', 'Name') !!}
                                {!! Form::text('name', null, ['id' => 'name', 'class' => 'form-control', 'placeholder' => 'Name']) !!}
                            </div>
                        </div>
                        <div class="col-md-6">

                        </div>
                    </div>

                </div>

                <div class="form-actions">
                    <a href="{{route('satuan.index')}}" class="btn btn-warning mr-1" onclick="return confirm('Apa anda yakin?')">
                        <i class="feather icon-corner-down-left"></i> Back
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-check-square-o"></i> Submit
                    </button>
                </div>
                {!! Form::close()  !!}
            </div>
        </div>
    </section>
@endsection
@push('js')
    {!! JsValidator::formRequest('App\Http\Requests\Master\Kategori\CreateRequest') !!}
@endpush

resources/views/page/master/satuan/edit.blade.php
@extends('layouts.app')

@section('content')

    <section id="description" class="card">
        <div class="card-header">
            <h4 class="card-title">Satuan</h4>
        </div>
        <div class="card-content">
            <div class="card-body">

                {!! Form::model($data,['route' => ['satuan.update', $data->id],'files' => true, 'method' => 'put', 'id' => 'form-task'])!!}
                <div class="form-body">
                    <div class="row">
                        <div class="col md-6">
                            <div class="form-group">
                                {!! Form::label('name', 'Name') !!}
                                {!! Form::text('name', null, ['id' => 'name', 'class' => 'form-control']) !!}
                            </div>
                        </div>
                        <div class="col md-6">
                        </div>
                    </div>

                </div>

                <div class="form-actions">
                    <a href="{{route('satuan.index')}}" class="btn btn-warning mr-1" onclick="return confirm('Apa anda yakin?')">
                        <i class="feather icon-corner-down-left"></i> Back
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-check-square-o"></i> Submit
                    </button>
                </div>
                {!! Form::close()  !!}
            </div>
        </div>
    </section>
@endsection

@push('js')
        {!! JsValidator::formRequest('App\Http\Requests\Master\Kategori\UpdateRequest') !!}
@endpush

resources/views/page/master/satuan/index.blade.php
@extends('layouts.app')

@section('content')
    <div id="description" class="card">
        <div class="card-header">
            <h4 class="card-title">Satuan</h4>
            <div class="col md-3">
                <a href="{{route('satuan.create')}}" class="btn btn-primary float-right" >Create</a>
            </div>
        </div>
        <div class="card-content">
            <div class="card-body">
                @if(Session::has('keterangan'))
                    <div class="alert alert-success alert-dismissible mb-2" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                        {{Session::get('keterangan')}}
                    </div>
                @endif
                <table class="table table-striped table-bordered dt-responsive" id="table1" width="100%">
                    <thead>
                    <th width="30px">No</th>
                    <th>Name</th>
                    <th width="140px">Action</th>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        const table1 =  $('#table1').DataTable({
            "processing": true,
            "serverSide": true,
            "responsive" :true,
            "ajax": window.location.href,
            "columns": [
                { data: 'DT_RowIndex', name: 'DT_RowIndex' , orderable: false, searchable: false, className: "text-right"},
                { data: "name"},
                { data: "action",  className: "text-center"},
            ]
        });
    </script>
@endpush